# -*- coding: utf-8 -*-
"""clustering algorithms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkV5JAA17ZhKb-LlgIDhhEr7rXXINjKU

K-Means Clustering
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

df=pd.read_csv('/content/Income.csv')

df.head()

plt.scatter(df['Age'],df['Income($)'])
plt.show

scaler=MinMaxScaler()
scaler.fit(df[['Age','Income($)']].values)
df[['Age','Income($)']]=scaler.transform(df[['Age','Income($)']].values)
df

kmeans=KMeans(n_clusters=3)
y_predicted=kmeans.fit_predict(df[['Age','Income($)']])
df['Cluster']=y_predicted
df.head()

centroids=kmeans.cluster_centers_
centroids

df1=df[df.Cluster==0]
df2=df[df.Cluster==1]
df3=df[df.Cluster==2]
plt.scatter(df1.Age,df1['Income($)'], color='r',label='Cluster1')
plt.scatter(df2.Age,df2['Income($)'], color='c',label='Cluster2')
plt.scatter(df3.Age,df3['Income($)'], color='b',label='Cluster3')
plt.scatter(centroids[:,0],centroids[:,1],color='green',marker='*',label='centroid')
plt.legend()

