# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XASe0gtjFiG07PZczmzIKLLF7ECguOEQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler

df=pd.read_csv('/content/Mall_Customers (2).csv')
df.head()

df_values=df[['Age','Annual Income (k$)']].values
df_values

scaler=MinMaxScaler()
scaler.fit(df[['Age','Annual Income (k$)']].values)
df[['Age','Annual Income (k$)']]=scaler.transform(df[['Age','Annual Income (k$)']].values)
df

plt.scatter(df['Age'],df['Annual Income (k$)'])

from sklearn.cluster import KMeans

wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10)
  kmeans.fit(df[['Age','Annual Income (k$)']])
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)

from sklearn.cluster import DBSCAN
dbscan=DBSCAN(eps=1,min_samples=5)

labels=dbscan.fit_predict(df[['Age','Annual Income (k$)']])
df['Cluster']=labels

